application:
  name: generic
  version: 0.0.1
  module: users

server:
  port: 9991
  context-path: /generic
  apiPath: /api/*
  timeZone: Europe/Madrid
  servlet:
    encoding:
      force-response: true
      charset: UTF-8
      enabled: true
      force: true

spring:
  application.name: generic
  mvc.servlet.path: /api/v1
  profiles:
    active: @spring.profiles.active@
  config:
    import:
      - application-base.yaml
      - optional:application-datasource.yaml
      - application-@spring.profiles.active@.yaml
