CREATE TABLE modules
(
    id_module   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code_module VARCHAR(3)                              NOT NULL,
    module      VARCHAR(200)                            NOT NULL
);

CREATE TABLE role_modules
(
    id_module BIGINT NOT NULL,
    id_role   BIGINT NOT NULL
);

CREATE TABLE roles
(
    id_role   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code_role VARCHAR(2)                              NOT NULL,
    role      VARCHAR(50)                             NOT NULL
);

CREATE TABLE user_roles
(
    id_role BIGINT NOT NULL,
    id_user BIGINT NOT NULL
);

CREATE TABLE users
(
    id_user        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username       VARCHAR(50)                             NOT NULL,
    password       VARCHAR(255)                            NOT NULL,
    email          VARCHAR(50)                             NOT NULL,
    enabled        BOOLEAN                                 NOT NULL,
    banned         BOOLEAN                                 NOT NULL,
    ban_date       TIMESTAMP WITH TIME ZONE,
    login_date     TIMESTAMP WITH TIME ZONE,
    login_attempts INTEGER
);

ALTER TABLE modules
    ADD CONSTRAINT pk_modules PRIMARY KEY (id_module),
    ADD CONSTRAINT uk_modules UNIQUE (code_module);

ALTER TABLE roles
    ADD CONSTRAINT pk_roles PRIMARY KEY (id_role),
    ADD CONSTRAINT uk_roles UNIQUE (code_role);

ALTER TABLE users
    ADD CONSTRAINT pk_users PRIMARY KEY (id_user),
    ADD CONSTRAINT uk_users_name UNIQUE (username),
    ADD CONSTRAINT uk_users_email UNIQUE (email);

ALTER TABLE role_modules
    ADD CONSTRAINT pk_role_modules PRIMARY KEY (id_module, id_role),
    ADD CONSTRAINT fk_rolmod_on_module FOREIGN KEY (id_module) REFERENCES modules (id_module),
    ADD CONSTRAINT fk_rolmod_on_role FOREIGN KEY (id_role) REFERENCES roles (id_role);

ALTER TABLE user_roles
    ADD CONSTRAINT pk_user_roles PRIMARY KEY (id_role, id_user),
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (id_role) REFERENCES roles (id_role),
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (id_user) REFERENCES users (id_user);