CREATE TABLE modules
(
    id_module   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code_module VARCHAR(3)                              NOT NULL,
    module      VARCHAR(200)                            NOT NULL,
    CONSTRAINT pk_modules PRIMARY KEY (id_module)
);

CREATE TABLE role_modules
(
    id_module BIGINT NOT NULL,
    id_role   BIGINT NOT NULL,
    CONSTRAINT pk_role_modules PRIMARY KEY (id_module, id_role)
);

CREATE TABLE roles
(
    id_role   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code_role VARCHAR(2)                              NOT NULL,
    role      VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id_role)
);

CREATE TABLE user_roles
(
    id_role BIGINT NOT NULL,
    id_user BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (id_role, id_user)
);

CREATE TABLE users
(
    id_user        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username       VARCHAR(50)                             NOT NULL,
    password       VARCHAR(255),
    email          VARCHAR(50),
    enabled        BOOLEAN                                 NOT NULL,
    banned         BOOLEAN                                 NOT NULL,
    ban_date       TIMESTAMP WITH TIME ZONE,
    login_date     TIMESTAMP WITH TIME ZONE,
    login_attempts INTEGER,
    CONSTRAINT pk_users PRIMARY KEY (id_user)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE role_modules
    ADD CONSTRAINT fk_rolmod_on_module FOREIGN KEY (id_module) REFERENCES modules (id_module);

ALTER TABLE role_modules
    ADD CONSTRAINT fk_rolmod_on_role FOREIGN KEY (id_role) REFERENCES roles (id_role);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (id_role) REFERENCES roles (id_role);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (id_user) REFERENCES users (id_user);